add some function

diff --git a/afewmore b/afewmore
--- a/afewmore
+++ b/afewmore
@@ -60,14 +60,6 @@ check_instance(){
     fi
 }
 
-# function to check the number is valid
-check_num(){
-    local re='^[1-9][0-9]*$'
-    if ! [[ $NUM_CP =~ $re ]] ; then
-        fatal "Error not a valid number"
-    fi
-}
-
 # (DO IT AFTER FETCH INFO)function to check the directory is exist
 check_dir(){
     msg "check the directory is exist..."
@@ -79,7 +71,33 @@ check_dir(){
     fi      
 }
 
+# function to check the number is valid
+check_num(){
+    local re='^[1-9][0-9]*$'
+    if ! [[ $NUM_CP =~ $re ]] ; then
+        fatal "Error not a valid number"
+    fi
+}
 
+
+
+# create instance
+create_instance(){
+    msg "create instance...."
+    local start_instance=$(aws ec2 run-instances --count $NUM_CP --image-id $IMAGE_ID --key-name $KEY_NAME --instance-type $INSTANCE_TYPE --placement AvailabilityZone="$AVA_ZONE" --security-group-ids $GROUP_ID --output json > test.txt)
+    if [ "$?" != "0" ];then
+        fatal "Can' create more instance"
+    fi
+    INSTANCE_ID_LIST=($(cat test.txt | grep InstanceId | awk '{print substr($2, 2, 19)}'))
+    local index=0
+    PUBLIC_DNS_LIST=()
+    for id in "${INSTANCE_ID_LIST[@]}"
+    do
+        PUBLIC_DNS_LIST[$index]=$(aws ec2 describe-instances --instance-ids $id --output text --query 'Reservations[].Instances[].{Public_Dns_Name:PublicDnsName}')
+        msg "target instance: <Instance_id : $id> @${PUBLIC_DNS_LIST[$index]}"
+        local index=$index+1
+    done
+}
 
 ##########################################
 #fetch information using the instance id
@@ -108,22 +126,20 @@ fetch_user(){
 }
 
 
-# create instance
-create_instance(){
-    msg "create instance...."
-    local start_instance=$(aws ec2 run-instances --count $NUM_CP --image-id $IMAGE_ID --key-name $KEY_NAME --instance-type $INSTANCE_TYPE --placement AvailabilityZone="$AVA_ZONE" --security-group-ids $GROUP_ID --output json > test.txt)
-    if [ "$?" != "0" ];then
-        fatal "Can' create more instance"
-    fi
-    INSTANCE_ID_LIST=($(cat test.txt | grep InstanceId | awk '{print substr($2, 2, 19)}'))
-    local index=0
-    PUBLIC_DNS_LIST=()
-    for id in "${INSTANCE_ID_LIST[@]}"
-    do
-        PUBLIC_DNS_LIST[$index]=$(aws ec2 describe-instances --instance-ids $id --output text --query 'Reservations[].Instances[].{Public_Dns_Name:PublicDnsName}')
-        msg "target instance: <Instance_id : $id> @${PUBLIC_DNS_LIST[$index]}"
-        local index=$index+1
-    done
+# transport function
+start_trans(){
+    msg "start transfer the data to target instance"
+    for DNS in "${PUBLIC_DNS_LIST[@]}"
+        do
+            local trans=$(ssh -o "StrictHostKeyChecking no" $USER@$SOURCE_DNS "tar -czf - $SOURCE_DIR"\
+             | ssh -o "StrictHostKeyChecking no" $USER@$DNS "tar -xzf - " >/dev/null 2>&1)
+            if [ "$?" == "0" ];then
+                 msg "Succuss upload file to $USER@$DNS"
+            else
+                 msg "Failed to upload file to $USER@$DNS"
+            fi 
+        done
+    msg "Task finished"
 }
 
 # wait until all new created instances initialized done
@@ -146,21 +162,7 @@ wait_for_initialized(){
 
 
 
-# transport function
-start_trans(){
-    msg "start transfer the data to target instance"
-    for DNS in "${PUBLIC_DNS_LIST[@]}"
-        do
-            local trans=$(ssh -o "StrictHostKeyChecking no" $USER@$SOURCE_DNS "tar -czf - $SOURCE_DIR"\
-             | ssh -o "StrictHostKeyChecking no" $USER@$DNS "tar -xzf - " >/dev/null 2>&1)
-            if [ "$?" == "0" ];then
-                 msg "Succuss upload file to $USER@$DNS"
-            else
-                 msg "Failed to upload file to $USER@$DNS"
-            fi 
-        done
-    msg "Task finished"
-}
+
 
 
 # main 
